nsnail/NetAdmin

src/backend/NetAdmin.AdmServer.Host/settings.json, src/backend/NetAdmin.Domain/DbMaps/Dependency/LiteImmutableEntity.cs, src/backend/NetAdmin.Domain/DbMaps/Dependency/LiteMutableEntity.cs, src/backend/NetAdmin.Host/Extensions/ServiceCollectionExtensions.cs, src/backend/NetAdmin.Host/Utils/SqlAuditor.cs, src/backend/NetAdmin.Infrastructure/commonSettings.json, src/backend/NetAdmin.SysComponent.Application/Services/Sys/JobService.cs, src/backend/NetAdmin.SysComponent.Application/Services/Sys/ToolsService.cs, src/backend/NetAdmin.SysComponent.Application/Services/Sys/VerifyCodeService.cs
=> fix: 🐛 时区问题

NetAdmin.sln.DotSettings
=> chore: 🔨 dotSettings

nuget.config, src/backend/NetAdmin.Domain/DbMaps/Sys/Sys_DicCatalog.cs, src/backend/NetAdmin.Domain/DbMaps/Sys/Sys_DicContent.cs, src/backend/NetAdmin.Domain/DbMaps/Sys/Sys_JobRecord.cs, src/backend/NetAdmin.Domain/DbMaps/Sys/Sys_Menu.cs, src/backend/NetAdmin.Domain/DbMaps/Sys/Sys_RequestLog.cs, src/backend/NetAdmin.Domain/DbMaps/Sys/Sys_Role.cs, src/backend/NetAdmin.Domain/DbMaps/Sys/Sys_RoleDept.cs, src/backend/NetAdmin.Domain/DbMaps/Sys/Sys_RoleMenu.cs, src/backend/NetAdmin.Domain/DbMaps/Sys/Sys_SiteMsgDept.cs, src/backend/NetAdmin.Domain/DbMaps/Sys/Sys_SiteMsgFlag.cs, src/backend/NetAdmin.Domain/DbMaps/Sys/Sys_SiteMsgRole.cs, src/backend/NetAdmin.Domain/DbMaps/Sys/Sys_SiteMsgUser.cs, src/backend/NetAdmin.Domain/DbMaps/Sys/Sys_User.cs, src/backend/NetAdmin.Domain/Dto/Sys/UserProfile/CreateUserProfileReq.cs, src/backend/NetAdmin.Infrastructure/Constant/Chars.cs
=> style: 💄 code format

src/backend/NetAdmin.SysComponent.Application/Services/Sys/JobService.cs, src/backend/NetAdmin.SysComponent.Application/Services/Sys/MenuService.cs, src/backend/NetAdmin.SysComponent.Application/Services/Sys/RoleService.cs, src/backend/NetAdmin.SysComponent.Application/Services/Sys/UserProfileService.cs, src/backend/NetAdmin.SysComponent.Application/Services/Sys/VerifyCodeService.cs
=> fix: 🐛 take count

src/frontend/admin/src/components/naColId/index.vue, src/frontend/admin/src/global.js, src/frontend/admin/src/views/sys/config/index.vue
=> feat: ✨ naColId组件

README.md, build/code.quality.props, scripts/switcher.furion.json, src/backend/NetAdmin.Host/Filters/DefaultApiResultHandler.cs, src/backend/NetAdmin.Infrastructure/NetAdmin.Infrastructure.csproj, src/backend/NetAdmin.SysComponent.Application/Services/Sys/UserService.cs
=> perf(backend): ⚡ nuget update

scripts/switcher.furion.json
=> chore: 🔨 switcher

Dockerfile, src/backend/NetAdmin.Infrastructure/NetAdmin.Infrastructure.csproj, src/backend/NetAdmin.Tests/NetAdmin.Tests.csproj
=> perf: ⚡ 升级至.net9 prev4

README.md
=> docs: 📝 readme

src/backend/NetAdmin.Domain/DbMaps/Sys/Sys_RequestLog.cs
=> fix: 🐛 字段顺序

src/backend/NetAdmin.Domain/DbMaps/Sys/Sys_RequestLog.cs, src/backend/NetAdmin.Domain/DbMaps/Sys/Sys_User.cs, src/backend/NetAdmin.Domain/Dto/Sys/User/LoginRsp.cs, src/backend/NetAdmin.Infrastructure/Constant/Chars.cs, src/backend/NetAdmin.SysComponent.Host/Jobs/ScheduledJob.cs
=> fix: 🐛 字段长度

build/code.quality.props, scripts/switcher.furion.json, src/backend/NetAdmin.Domain/DbMaps/Dependency/Fields/IFieldCreatedClient.cs, src/backend/NetAdmin.Domain/DbMaps/Dependency/SimpleEntity.cs, src/backend/NetAdmin.Domain/DbMaps/Sys/Sys_JobRecord.cs, src/backend/NetAdmin.Domain/DbMaps/Sys/Sys_RequestLog.cs, src/backend/NetAdmin.Domain/Dto/Sys/RequestLog/QueryRequestLogRsp.cs, src/backend/NetAdmin.Host/Utils/RequestLogger.cs, src/backend/NetAdmin.Host/Utils/SqlAuditor.cs, src/backend/NetAdmin.Infrastructure/Constant/Chars.cs, src/backend/NetAdmin.Infrastructure/NetAdmin.Infrastructure.csproj, src/backend/NetAdmin.SysComponent.Application/Services/Sys/RequestLogService.cs, src/backend/NetAdmin.SysComponent.Host/Subscribers/OperationLogger.cs, src/backend/NetAdmin.Tests/WebApiTestBase.cs, src/frontend/admin/src/components/scSelectFilter/index.vue, src/frontend/admin/src/layout/components/userbar.vue, src/frontend/admin/src/utils/preload.js, src/frontend/admin/src/views/sys/log/login/index.vue, src/frontend/admin/src/views/sys/log/operation/index.vue
=> fix: 🐛 操作日志不显示userName

README.md
=> docs: 📝 readme文档更新

package.json, src/backend/NetAdmin.Application/Services/RepositoryService.cs, src/backend/NetAdmin.SysComponent.Application/Services/Sys/ApiService.cs, src/backend/NetAdmin.SysComponent.Application/Services/Sys/ConfigService.cs, src/backend/NetAdmin.SysComponent.Application/Services/Sys/DeptService.cs, src/backend/NetAdmin.SysComponent.Application/Services/Sys/DicContentService.cs, src/backend/NetAdmin.SysComponent.Application/Services/Sys/JobRecordService.cs, src/backend/NetAdmin.SysComponent.Application/Services/Sys/JobService.cs, src/backend/NetAdmin.SysComponent.Application/Services/Sys/RequestLogService.cs, src/backend/NetAdmin.SysComponent.Application/Services/Sys/RoleService.cs, src/backend/NetAdmin.SysComponent.Application/Services/Sys/SiteMsgService.cs, src/backend/NetAdmin.SysComponent.Application/Services/Sys/UserService.cs, src/backend/NetAdmin.SysComponent.Application/Services/Tpl/ExampleService.cs, src/frontend/admin/package.json
=> refactor: ♻️ 抽取公共导出方法

src/backend/NetAdmin.Domain/DbMaps/Sys/Sys_LoginLog.cs, src/backend/NetAdmin.Domain/Dto/Dependency/DynamicFilterInfo.cs, src/backend/NetAdmin.Domain/Dto/Sys/LoginLog/ExportLoginLogRsp.cs, src/backend/NetAdmin.Domain/Dto/Sys/LoginLog/QueryLoginLogRsp.cs, src/backend/NetAdmin.SysComponent.Application/Services/Sys/ToolsService.cs, src/frontend/admin/src/components/naInfo/index.vue, src/frontend/admin/src/global.js, src/frontend/admin/src/views/sys/cache/index.vue, src/frontend/admin/src/views/sys/log/login/index.vue, src/frontend/admin/src/views/sys/log/operation/index.vue
=> refactor: ♻️ 批量查询ip归属地

src/frontend/admin/src/layout/components/userbar.vue
=> chore: 🔨 userbar下拉菜单弹出方式

src/backend/NetAdmin/NetAdmin.SysComponent.Application/Services/Sys/UserService.cs, src/frontend/admin/src/views/sys/user/index.vue
=> chore: 🔨 用户管理-角色排序

src/frontend/admin/src/components/naSearch/index.vue
=> fix: 🐛 导出界面报错

src/frontend/admin/src/components/naColUser/index.vue, src/frontend/admin/src/style/app.scss
=> refactor: ♻️ 样式优化

src/frontend/admin/src/components/scSelectFilter/index.vue
=> feat: ✨ select-filter badge icon

scripts/rename.csx
=> build: 📦 rename.csx

src/backend/NetAdmin/NetAdmin.Domain/DbMaps/Sys/Sys_DocContent.cs, src/backend/NetAdmin/NetAdmin.Domain/DbMaps/Sys/Sys_Job.cs, src/backend/NetAdmin/NetAdmin.Domain/DbMaps/Sys/Sys_JobRecord.cs, src/backend/NetAdmin/NetAdmin.Domain/DbMaps/Sys/Sys_LoginLog.cs, src/backend/NetAdmin/NetAdmin.Domain/DbMaps/Sys/Sys_RequestLogDetail.cs, src/backend/NetAdmin/NetAdmin.Domain/DbMaps/Sys/Sys_Role.cs, src/backend/NetAdmin/NetAdmin.Domain/DbMaps/Sys/Sys_SiteMsg.cs, src/backend/NetAdmin/NetAdmin.Domain/DbMaps/Sys/Sys_UserProfile.cs, src/backend/NetAdmin/NetAdmin.Infrastructure/Constant/Chars.cs
=> refactor: ♻️ 减少一些条件编译语句

.gitmodules
=> build: 📦 更新子模块

.gitmodules, NetAdmin.sln, build/code.quality.props, src/backend/NetAdmin/NetAdmin.Infrastructure/NetAdmin.Infrastructure.csproj
=> build: 📦 修复项目引用路径问题

NetAdmin.sln
=> style: 💄 解决方案文件段落整理

src/backend/NetAdmin/NetAdmin.Infrastructure/Extensions/ISelectExtensions.cs
=> chore: 🔨 iSelect 扩展方法增强

assets/seed-data/Sys_Menu.json
=> chore: 🔨 sys_Menu.json

.drone/workflows/README.md, NetAdmin.sln, scripts/sync.sln.files.csx, src/backend/NetAdmin/NetAdmin.Application/Services/RepositoryService.cs, src/backend/NetAdmin/NetAdmin.SysComponent.Application/Services/Sys/JobService.cs, src/backend/NetAdmin/NetAdmin.SysComponent.Application/Services/Sys/UserProfileService.cs, src/backend/NetAdmin/NetAdmin.SysComponent.Application/Services/Sys/UserService.cs, src/backend/NetAdmin/NetAdmin.SysComponent.Cache/Sys/RequestLogCache.cs, src/backend/NetAdmin/NetAdmin.SysComponent.Host/Extensions/ServiceCollectionExtensions.cs
=> fix: 🐛 version lock

scripts/git.config.cmd
=> build: 📦 git.config

build/code.quality.props, src/frontend/admin/src/components/scTable/index.vue
=> chore: 🔨 表格行双击查看

src/backend/NetAdmin/NetAdmin.Domain/Extensions/ISelectExtensions.cs
=> fix: 🐛 build error

Directory.Build.props, build/code.quality.props, src/backend/NetAdmin/NetAdmin.Infrastructure/NetAdmin.Infrastructure.csproj
=> perf: ⚡ nuget update

build/code.quality.props, src/backend/NetAdmin/NetAdmin.Infrastructure/EventBus/DefaultEventPublisher.cs, src/backend/NetAdmin/NetAdmin.Infrastructure/EventBus/IEventPublisher.cs
=> chore: 🔨 事件发布器接口通道数量

README.md
=> fix: flowchart显示问题

build/code.quality.props, src/backend/NetAdmin/NetAdmin.Domain/DbMaps/Sys/Sys_Api.cs, src/backend/NetAdmin/NetAdmin.Domain/DbMaps/Sys/Sys_Dept.cs, src/backend/NetAdmin/NetAdmin.Domain/DbMaps/Sys/Sys_DicCatalog.cs, src/backend/NetAdmin/NetAdmin.Domain/DbMaps/Sys/Sys_DocCatalog.cs, src/backend/NetAdmin/NetAdmin.Domain/DbMaps/Sys/Sys_Menu.cs, src/backend/NetAdmin/NetAdmin.Domain/DbMaps/Sys/Sys_Role.cs, src/backend/NetAdmin/NetAdmin.Domain/DbMaps/Sys/Sys_SiteMsg.cs, src/backend/NetAdmin/NetAdmin.Domain/DbMaps/Sys/Sys_User.cs, src/backend/NetAdmin/NetAdmin.Domain/NetAdmin.Domain.csproj, src/backend/NetAdmin/NetAdmin.Infrastructure/NetAdmin.Infrastructure.csproj, src/backend/NetAdmin/NetAdmin.Tests/NetAdmin.Tests.csproj, src/frontend/admin/package.json, src/frontend/admin/src/components/scUpload/multiple.vue
=> refactor: ♻️ 框架代码同步

src/backend/NetAdmin/NetAdmin.Domain/Enums/Sys/JobStatues.cs, src/backend/NetAdmin/NetAdmin.Domain/NetAdmin.Domain.csproj, src/frontend/admin/src/components/scSelect/index.vue
=> chore: 🔨 框架代码同步

src/frontend/admin/src/utils/request.js
=> fix: 🐛 文件下载编码匹配

src/backend/NetAdmin/NetAdmin.SysComponent.Application/Services/Sys/CodeTemplateService.cs
=> fix: 🐛 编译错误

src/backend/NetAdmin/NetAdmin.SysComponent.Host/Subscribers/OperationLogger.cs
=> fix: 🐛 build err
